org: niv3kelpato
app: streamtechroyale
service: streamtechroyale
frameworkVersion: '3'

params:
  default:
    Creator: ${self:service}-${sls:stage}-Creator
    Clip: ${self:service}-${sls:stage}-Clip
    UserClipLiked: ${self:service}-${sls:stage}-UserClipLiked
    UserRepresentation: ${self:service}-${sls:stage}-UserRepresentation
    Prize: ${self:service}-${sls:stage}-Prize
    TournamentWins: ${self:service}-${sls:stage}-TournamentWins
    RoulletteWins: ${self:service}-${sls:stage}-RoulletteWins
    RoulletteRestriction: ${self:service}-${sls:stage}-RoulletteRestriction

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:Query'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: 
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${param:Creator}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${param:Clip}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${param:Prize}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${param:TournamentWins}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${param:RoulletteWins}

resources:
  Resources:
    Creator:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:Creator}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Clip:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:Clip}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    UserClipLiked:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:UserClipLiked}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: clipId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: clipId
            KeyType: RANGE
    Prize:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:Prize}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    TournamentWins:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:TournamentWins}
        AttributeDefinitions:
          - AttributeName: roundId
            AttributeType: N
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: roundId
            KeyType: HASH
    RoulletteWins:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:RoulletteWins}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    RoulletteRestriction:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:RoulletteRestriction}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
    UserRepresentation:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${param:UserRepresentation}
        AttributeDefinitions:
          - AttributeName: creatorId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: creatorId
            KeyType: HASH
          - AttributeName: userId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: 'KEYS_ONLY'