org: niv3kelpato
app: streamtechroyale
service: streamtechroyale
frameworkVersion: '3'

params:
  default:
    Creator: ${self:service}-${sls:stage}-Creator
    Clip: ${self:service}-${sls:stage}-Clip
    StaticBucket: ${self:service}-${sls:stage}-StaticBucket

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:Get*'
            - 'dynamodb:Scan*'
            - 'dynamodb:Query'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: 
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${param:Creator}
            - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${param:Clip}
        - Effect: 'Allow'
          Action:
            - "s3:PutObject"
            - "s3:PutObjectAcl" 
          Resource: 
            - arn:aws:s3:::${param:StaticBucket}/*

resources:
  Resources:
    Creator:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
        TableName: ${param:Creator}
    Clip:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
        TableName: ${param:Clip}